 import type { Metadata } from "next";
import localFont from "next/font/local";
import {Roboto} from "next/font/google";

import Header from './Components/Layout/Header';
import "./globals.css";
import Footer from './Components/Layout/Footer';
import { CartProvider } from "./context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const roboto = Roboto({
  subsets: ['latin'], // Specify at least one subset like 'latin' or 'cyrillic'
  weight: ['400', '700'], // Optional: Include weights if needed
  preload: true, // Ensure preloading is explicitly enabled (default)
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.className} ${geistMono.variable} antialiased`}
      >
        <Header/>
         <CartProvider>{children}</CartProvider>
        <Footer />
      </body>
    </html>
  );
}